### ISSUE TITLE
安装插件后<!--more-->标签失效

### ISSUE THREAD

**Issue by Cpaulyz** [chekun/hexo-excerpt#14]
使用hexo next 最新版本主题 
安装该插件后标签失效，检查了很久，可惜水平不够没检查出哪里有问题，卸载了插件试了一下，标签就可以用了。

**Comment by aleung** [comment]
似乎这个插件启用后，文本中原有的 `<!--more-->` 标签就被忽略了。

建议逻辑改为：文本中带有 `<!--more-->` 标签，使用已有标签；没有标签时才自动按照段落数分割。

**Comment by chekun** [comment]
有的哦，默认就是 `<!--more-->` 标记优先的

代码如下：

https://github.com/chekun/hexo-excerpt/blob/master/lib/hexo-excerpt.js#L36

**Comment by aleung** [comment]
那奇怪了，等我有空再测试一下。

**Comment by aleung** [comment]
哦，知道原因了：代码里正则表达式只精确匹配 `<!-- more -->`，如果里面没有空格或者多了空格就匹配不上。但在实际使用中，空格数量可以不定的。建议增强一下这个正则表达式。

**Comment by chekun** [comment]
@aleung 你意思是more前后的空格不定吗？标准的就应该是 `<!-- more -->`吧，😄

**Comment by aleung** [comment]
但是，不写空格也是生效的。所以我的文章里有些标签是没有空格的。我估计并没有标准要求前后各一个空格，只是要求是一行HTML注释，里面包含`more`。

**Comment by chekun** [comment]
@aleung 没问题，我来升级下

**Comment by chekun** [comment]
@aleung @Cpaulyz

已更新

**Comment by aleung** [comment]
安装新版本测试还是不行。加了些debug输出，将`post.content`打印出来，发现 `<!-- more -->`早已经被转译为这样的一行：

```
<a id="more"></a>
```

因此正则表达式匹配不上。

我用的是 NexT 主题，不知道是否与它有关。

Hexo：4.2.0
NexT：7.7.2

**Comment by chekun** [comment]
@aleung 已经更新了1.1.6版本，你试试。

应该是hexo后来的版本更新了，在generator流程之前之前more就被转换了，目前做了兼容。

**Comment by aleung** [comment]
谢谢，你反应真快 👍 我今晚试试。

**Comment by aleung** [comment]
这个版本正常了，谢谢

**Comment by chekun** [comment]
@aleung 不客气，有问题及时反馈~~~
