### ISSUE TITLE
how to control the number of word //怎么控制字数

### ISSUE THREAD

**Issue by z1027001** [chekun/hexo-excerpt#15]
I want to control he number of word but I don‘t know how

**Comment by chekun** [comment]
控制字数是啥意思？

**Comment by xfdywy** [comment]
我猜他的意思是，以前版本自动阶段文章的时候，可以选择截断到第多少个单词显示在首页上。然后你这个插件是否也可以选择截断到第多少个单词这种模式？不过目前看下来貌似原理不太相同

**Comment by Richard-Zheng** [comment]
同样需要这个功能。NexT在7.5.0把auto_excerpt这个功能删去了。现在我想直接截取文章的前150个字作为摘要，请问可以实现吗？

**Comment by chekun** [comment]
@Richard-Zheng 取前N个字还是比较简单的，你可以改改我的代码，毕竟目前这个插件不是靠截取字符的。思路就是把html代码清掉，然后去前N个字即可。
