### ISSUE TITLE
关于depth这个属性是如何使用的

### ISSUE THREAD

**Issue by Tanky-Zhang** [chekun/hexo-excerpt#19]
您好，我看到readme中有个属性是depth，我想知道的是这个属性是控制展示的行数的嘛，如果是的话为什么修改这个参数没有任何变化，如果不是那么想咨询下我们应当如何控制展示的行数呢

**Comment by chekun** [comment]
不是控制【行数】用的，这个插件不是基于行数生成摘要的，是基于tag的，就是说post.content中的一级tag的数量来控制的，比如你的内容如下：

```
<div>1</div>
<div>2</div>
<div>3</div>
<div>4</div>
<div>5</div>
<div>6</div>
<div>7</div>
<div>8</div>
<div>9</div>
<div>10</div>
```

`depth`设置为2，得到的摘要应该就是： 

```
<div>1</div>
<div>2</div>
```

如果你还是希望行数，可以自行使用`<!--more-->`来手动控制哈。

**Comment by Tanky-Zhang** [comment]
好的，非常感谢您的回答。

**Comment by Tanky-Zhang** [comment]
> 不是控制【行数】用的，这个插件不是基于行数生成摘要的，是基于tag的，就是说post.content中的一级tag的数量来控制的，比如你的内容如下：
> 
> 
> 
> ```
> 
> <div>1</div>
> 
> <div>2</div>
> 
> <div>3</div>
> 
> <div>4</div>
> 
> <div>5</div>
> 
> <div>6</div>
> 
> <div>7</div>
> 
> <div>8</div>
> 
> <div>9</div>
> 
> <div>10</div>
> 
> ```
> 
> 
> 
> `depth`设置为2，得到的摘要应该就是： 
> 
> 
> 
> ```
> 
> <div>1</div>
> 
> <div>2</div>
> 
> ```
> 
> 
> 
> 如果你还是希望行数，可以自行使用`<!--more-->`来手动控制哈。

好的👌，非常感谢您的回答
