### ISSUE TITLE
Use except-html

### ISSUE THREAD

**Issue by martinheidegger** [chekun/hexo-excerpt#2]
Hello there! I wonder if you would consider to accept a PR that uses https://github.com/martinheidegger/excerpt-html ?

**Comment by chekun** [comment]
@martinheidegger Yes, of course!

**Comment by chekun** [comment]
@martinheidegger hi, is this still going on? 😃

**Comment by martinheidegger** [comment]
Oh my - yes - but I havn't found the time due to heavy load on other tasks and I am busy until mid Nov.
