### ISSUE TITLE
错误layout和插件不适配

### ISSUE THREAD

**Issue by tedcy** [chekun/hexo-excerpt#40]
主页没有问题，渲染生成的public下的文件全部为0字节

```
$ ll -h public/2022/7/17/quick-sort/index.html
-rw-r--r-- 1 Administrator 197121 0 七月   26 14:52 public/2022/7/17/quick-sort/index.html
```

版本依赖如下所示
```
npm ls --depth=0
+-- hexo@6.2.0
+-- hexo-excerpt@1.3.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@5.0.0
+-- hexo-renderer-stylus@2.1.0
+-- hexo-server@3.0.0
`-- hexo-theme-landscape@0.0.3
```

hexo-auto-excerpt则没有这个问题，但是个人觉得按层数的摘要预览比按字数更科学和美观，希望可以修复

**Comment by chekun** [comment]
估计是hexo API 有变动，我来看看哈

**Comment by chekun** [comment]
@tedcy 你好，我升级了hexo为6.2.0版本，`npm run test` 一切正常。

我又新建了hexo项目，generate 命令出来的文件，测试也正常

```
❯ hexo -v
hexo: 6.2.0
hexo-cli: 4.3.0
```

----------------------
可以上传一下可以复现的最小代码不？

**Comment by tedcy** [comment]
我回退了hexo版本也不行。。。
```
   return {
      path: post.path,
      data: post,
      layout: post.layout
    };
```
然后下午自己尝试乱改了一下，去掉了path那一行或者layout那一行都可以恢复正常

我看看怎么复现一个最小版本

**Comment by tedcy** [comment]
大佬，我已经定位问题了
我以前用的jeklly需要指定layout为default，而hexo默认的layout为post
当我的文章全部指定了不存在的layout以后，hexo不会有问题
但是安装了大佬的插件以后，就会出现渲染失败的问题

在大佬的代码中去掉了path那一行或者layout那一行也可以恢复正常

我目前把所有的layout都改对了，也就好了

**Comment by chekun** [comment]
好滴
